#!/usr/bin/env python3
"""Aggregate review JSON outputs from all three reviewers and post PR comment."""
import json, os, sys
from pathlib import Path

def load_review(path: str) -> dict:
    try:
        return json.loads(Path(path).read_text())
    except (FileNotFoundError, json.JSONDecodeError):
        return {"status": "error", "findings": [], "count": 0}

SEVERITY_EMOJI = {"critical": "CRIT", "high": "HIGH", "medium": "MED", "low": "LOW", "warning": "WARN"}

def format_findings(findings: list) -> str:
    if not findings:
        return "  (none)"
    groups = {"critical": [], "high": [], "medium": [], "low": [], "warning": []}
    for f in findings:
        groups.get(f.get("severity", "low"), []).append(f)
    lines = []
    for sev in ["critical", "high", "medium", "low", "warning"]:
        items = groups[sev]
        if not items:
            continue
        tag = SEVERITY_EMOJI[sev]
        for item in items:
            lines.append(f"  [{tag}] `{item.get('file','?')}` -- {item.get('message','')}")
    return "\n".join(lines)

def main():
    security_path = sys.argv[1] if len(sys.argv) > 1 else "/tmp/security-review.json"
    cncf_path = sys.argv[2] if len(sys.argv) > 2 else "/tmp/cncf-review.json"
    quality_path = sys.argv[3] if len(sys.argv) > 3 else "/tmp/quality-review.json"
    changed_files = sys.argv[4:] if len(sys.argv) > 4 else []

    security = load_review(security_path)
    cncf = load_review(cncf_path)
    quality = load_review(quality_path)

    all_findings = security.get("findings", []) + cncf.get("findings", []) + quality.get("findings", [])
    critical = sum(1 for f in all_findings if f.get("severity") == "critical")
    high = sum(1 for f in all_findings if f.get("severity") == "high")
    medium = sum(1 for f in all_findings if f.get("severity") == "medium")
    low = sum(1 for f in all_findings if f.get("severity") == "low")

    verdict = "APPROVED"
    if critical > 0:
        verdict = "CHANGES REQUESTED (critical)"
    elif high > 0:
        verdict = "CHANGES REQUESTED (high)"
    elif medium > 3:
        verdict = "REVIEW RECOMMENDED"

    pr_number = os.environ.get("PR_NUMBER", "?")
    repo = os.environ.get("REPO", "?")
    sha = os.environ.get("PR_SHA", "?")[:7]

    comment = f"""🤖 **Hermes Multi-Agent PR Review**

**Repo:** {repo} | **PR:** #{pr_number} | **SHA:** `{sha}`
**Files reviewed:** {len(changed_files)}

---

**> Security Review**
{format_findings(security.get("findings", []))}

**> CNCF Best Practices**
{format_findings(cncf.get("findings", []))}

**> Code Quality**
{format_findings(quality.get("findings", []))}

---

**Summary:** {critical} critical / {high} high / {medium} medium / {low} low
**Verdict: {verdict}**

---
_Auto-generated by platform-eng-review/.github/workflows/scripts/_
"""
    comment_path = "/tmp/pr-review-comment.md"
    Path(comment_path).write_text(comment)
    print(f"Review comment written to {comment_path}")
    print(json.dumps({
        "verdict": verdict,
        "critical": critical, "high": high, "medium": medium, "low": low,
        "total": len(all_findings),
    }))

if __name__ == "__main__":
    main()
